entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    swarmMode: true

api:
  dashboard: false

certificatesResolvers:
  myresolver:
    acme:
      email: '{{ env "EMAIL" }}'
      storage: /certs/acme.json
      httpChallenge:
        entryPoint: web
